# Generated by Django 2.0.7 on 2018-07-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_group_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='students',
            field=models.ManyToManyField(through='school.StudentAssignment', to='school.Student'),
        ),
    ]
