# Generated by Django 2.0.7 on 2018-08-01 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180801_1316'),
    ]

    operations = [

        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('create_assignment', 'Create an Assignment object'), ('change_assignment', 'Update an Assignment object'), ('delete_assignment', 'Delete an Assignment object'))},
        ),
    ]
