# Generated by Django 2.0.7 on 2018-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_assignment_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='room_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='group',
            name='language',
            field=models.CharField(max_length=25),
        ),
    ]
