# Generated by Django 2.0.7 on 2018-08-02 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20180801_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'permissions': (('school.create_assignment', 'Create an Assignment object'), ('school.change_assignment', 'Update an Assignment object'), ('school.delete_assignment', 'Delete an Assignment object'))},
        ),
    ]
